# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-18 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='state_employees',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
