# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191018_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
