# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-20 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191018_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='class_list',
            field=models.ManyToManyField(blank=True, null=True, to='user.ClassList', verbose_name='已报班级'),
        ),
    ]
