# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191025_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='icon',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='menus',
            field=models.BooleanField(default=False, verbose_name='是否为菜单'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(to='user.Roles', verbose_name='角色'),
        ),
    ]
