# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-28 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191025_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('icon', models.CharField(blank=True, max_length=24, null=True)),
                ('weight', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='permissions',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Permissions'),
        ),
        migrations.AddField(
            model_name='permissions',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Menu'),
        ),
    ]
