# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-29 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191028_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='alias',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
